- name: Install software that is required for Minecraft
  become: true
  ansible.builtin.package:
    name: [openjdk-17-jre-headless, polkitd]

- name: Making sure the service user exists
  become: true
  ansible.builtin.user:
    name: "{{ minecraft_be_user }}"
    state: present
    password: "*"

- name: Make sure we have our working directory
  ansible.builtin.file:
    path: "{{ minecraft_be_dir }}"
    state: directory
    owner: "{{ minecraft_be_user }}"
    mode: "755"

- name: Checking to see if we have a server configuration file
  ansible.builtin.stat:
    path: "{{ minecraft_be_dir }}/server.properties"
  register: config_file

- name: Downloading Minecraft
  when: minecraft_be_force_install or not config_file.stat.exists
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ minecraft_be_url }}"
    dest: "{{ minecraft_be_dir }}"
    exclude: "{{ minecraft_be_preserve_files }}"
    owner: "{{ minecraft_be_user }}"

- name: Creating allowlist.json
  become: true
  ansible.builtin.copy:
    content: '{{ minecraft_be_allowlist }}'
    dest: "{{ minecraft_be_dir }}/allowlist.json"
    owner: "{{ minecraft_be_user }}"
    mode: "600"
  notify: Restarting systemd service

- name: Creating permissions.json
  become: true
  ansible.builtin.copy:
    content: '{{ minecraft_be_permissions }}'
    dest: "{{ minecraft_be_dir }}/permissions.json"
    owner: "{{ minecraft_be_user }}"
    mode: "600"
  notify: Restarting systemd service

- name: Creating server.properties
  when: not config_file.stat.exists
  become: true
  ansible.builtin.copy:
    content: ''
    dest: "{{ minecraft_be_dir }}/server.properties"
    owner: "{{ minecraft_be_user }}"
    mode: "600"
  notify: Restarting systemd service

- name: Setting whether to log content errors
  become: true
  ansible.builtin.lineinfile:
    regex: '^content-log-file-enabled='
    line: content-log-file-enabled={{ minecraft_be_content_logging }}
    dest: "{{ minecraft_be_dir }}/server.properties"
  notify: Restarting systemd service

- name: Setting server port for IPv4
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ minecraft_be_dir }}/server.properties"
    regex: '^server-port=.*'
    line: server-port={{ minecraft_be_ipv4_port }}
  notify: Restarting systemd service

- name: Setting server port for IPv6
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ minecraft_be_dir }}/server.properties"
    regex: '^server-portv6=.*'
    line: server-portv6={{ minecraft_be_ipv6_port }}
  notify: Restarting systemd service

- name: Deploying systemd service file
  become: true
  ansible.builtin.template:
    src: templates/minecraftbe.service.j2
    dest: /etc/systemd/system/{{ minecraft_be_service_name }}.service
    owner: root
    mode: "644"
  notify: Deploying systemd service
